=== JesusLugo2002/1DAW/LND/unidad-06/tareas/tarea04-dtd-xsd/solucion-xsd/instituto.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.misitio.com" xmlns="http://www.misitio.com" elementFormDefault="qualified">
    <xs:element name="instituto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="clase" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alumno" maxOccurs="30">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre"/>
                                        <xs:element name="apellidos"/>
                                    </xs:sequence>
                                    <xs:attribute name="sexo" type="xs:string"/>
                                    <xs:attribute name="cial" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="grupo" type="xs:string"/>
                        <xs:attribute name="curso" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JesusLugo2002/1DAW/LND/unidad-07/tareas/tarea03-xsd-alumnos/solucion-xsd/xml_asociado_a_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<instituto xmlns="http://www.misitio.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.misitio.com instituto.xsd">
    <clase grupo="Desarrollo de Aplicaciones Web" curso="1">
        <alumno sexo="H" cial="A92C950D93">
            <nombre>Juan</nombre>
            <apellidos>Pérez Márquez</apellidos>
        </alumno>
        <alumno sexo="M" cial="A95C950D93">
            <nombre>Eva </nombre>
            <apellidos>Álvarez Marchena</apellidos>
        </alumno>
    </clase>
    <clase grupo="Desarrollo de Aplicaciones Web" curso="2">
        <alumno sexo="M" cial="A93X942D95">
            <nombre>Julia </nombre>
            <apellidos>Pérez González </apellidos>
        </alumno>
        <alumno sexo="H" cial="A95C740D74">
            <nombre>Manuel </nombre>
            <apellidos>López López </apellidos>
        </alumno>
    </clase>
</instituto>
